# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-30 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertel', models.CharField(max_length=100)),
                ('userpassword', models.CharField(max_length=200)),
                ('useremail', models.CharField(max_length=100)),
                ('usertoken', models.CharField(max_length=200)),
            ],
        ),
    ]
